In [28]:
import torch
import torch.nn as nn
import os

import numpy as np 
import pandas as pd
import datetime
import pickle
import time
import random

In [29]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [30]:
class win_identifer_model(nn.Module):
    def __init__(self, layers):
        super(win_identifer_model, self).__init__()
        modules = nn.ModuleList([nn.Flatten(), nn.Linear(6, layers[0]), nn.Sigmoid()])

        for idx, size in enumerate(layers[:-1]):
            modules.append(nn.Linear(size, layers[idx + 1]))
            modules.append(nn.Sigmoid())

        modules.append(nn.Linear(layers[-1], 1))
        self.layers = nn.Sequential(*modules)

    def forward(self, x):
        return self.layers(x)

In [35]:
def evaluate (model, file_name):
    df = pd.read_csv(os.path.join('data',f'{file_name}.csv'), index_col=0)

    for index, row in df.iterrows():
        input_np = row.drop(labels=['win','trio_win']).to_numpy()
        input_tensor = torch.tensor(input_np, dtype=torch.float).unsqueeze(dim=0)
        # print(input_tensor)
        __, predicted = torch.max(model(input_tensor).data, 1)
        print(predicted, row[['win']].to_numpy())

In [36]:
in_path = os.path.join('model_configs')

layers = [8, 16, 32, 64, 32, 16, 8, 4]

for model_file in [f for f in os.listdir(in_path) if not f.startswith('.')]:
    model = win_identifer_model(layers)
    model.load_state_dict(torch.load(os.path.join(in_path, model_file)))

    evaluate(model, model_file)

tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [1.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [1.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [1.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [1.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [1.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [1.]
tensor([0]) [1.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0.]
tensor([0]) [0