In [49]:
from typing import Dict, Text

import os
import numpy as np
import pandas as pd
import tensorflow as tf
import pprint

import tensorflow_ranking as tfr
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

from data_cleanup import sample_listwise

In [ ]:
ratings = tfds.load("movielens/100k-ratings", split="train")
movies = tfds.load("movielens/100k-movies", split="train")

ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
    "user_rating": x["user_rating"],
})
movies = movies.map(lambda x: x["movie_title"])

unique_movie_titles = np.unique(np.concatenate(list(movies.batch(1000))))
unique_user_ids = np.unique(np.concatenate(list(ratings.batch(1_000).map(
    lambda x: x["user_id"]))))

In [21]:
tf.random.set_seed(42)

# Split between train and tests sets, as before.
shuffled = ratings.shuffle(100_000, seed=42, reshuffle_each_iteration=False)

train = shuffled.take(80_000)
test = shuffled.skip(80_000).take(20_000)

# We sample 50 lists for each user for the training data. For each list we
# sample 5 movies from the movies the user rated.
# edited /Users/alexlee/miniconda3/envs/hkjc-tf/lib/python3.11/site-packages/tensorflow_recommenders/examples/movielens.py
train = tfrs.examples.movielens.sample_listwise(
    train,
    num_list_per_user=50,
    num_examples_per_list=5,
    seed=42
)
test = tfrs.examples.movielens.sample_listwise(
    test,
    num_list_per_user=1,
    num_examples_per_list=5,
    seed=42
)

In [64]:
df = pd.read_csv(os.path.join('data','all_races_cleaned.csv'), index_col=0)

ratings = pd.DataFrame()
ratings['movie_title'] = df['horse_colour'].astype(str)
ratings['user_id'] = df['race_index'].astype(str)
ratings['timestamp'] = df['horse_weight'].astype('int64')
ratings['user_rating'] = df['place'].astype('float32')
ratings = tf.data.Dataset.from_tensor_slices(dict(ratings))

movies = pd.DataFrame()
movies['movie_title'] = df['horse_colour'].astype(str)
movies = tf.data.Dataset.from_tensor_slices(dict(movies))

tf.random.set_seed(42)
shuffled = ratings.shuffle(100, seed=42, reshuffle_each_iteration=False)

split = 0.8

train = shuffled.take(int(split * len(shuffled)))
test = shuffled.skip(int(split * len(shuffled))).take(int((1-split) * len(shuffled)))

train = sample_listwise(
    train,
    num_list_per_user=50,
    num_examples_per_list=5,
    seed=42
)
test = sample_listwise(
    test,
    num_list_per_user=1,
    num_examples_per_list=5,
    seed=42
)

cached_train = train.shuffle(100).batch(8192).cache()
cached_test = test.batch(4096).cache()

train

In [65]:
for example in train.take(1):
    pprint.pprint(example)

{'movie_title': <tf.Tensor: shape=(5,), dtype=string, numpy=array([b'brown', b'bay', b'bay', b'bay', b'bay'], dtype=object)>,
 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'2023546.0'>,
 'user_rating': <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 2.,  6.,  8., 10.,  3.], dtype=float32)>}


In [66]:
class RankingModel(tfrs.Model):

  def __init__(self, loss):
    super().__init__()
    embedding_dimension = 32

    # Compute embeddings for users.
    self.user_embeddings = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
        vocabulary=unique_user_ids),
      tf.keras.layers.Embedding(len(unique_user_ids) + 2, embedding_dimension)
    ])

    # Compute embeddings for movies.
    self.movie_embeddings = tf.keras.Sequential([
      tf.keras.layers.StringLookup(
        vocabulary=unique_movie_titles),
      tf.keras.layers.Embedding(len(unique_movie_titles) + 2, embedding_dimension)
    ])

    # Compute predictions.
    self.score_model = tf.keras.Sequential([
      # Learn multiple dense layers.
      tf.keras.layers.Dense(256, activation="relu"),
      tf.keras.layers.Dense(64, activation="relu"),
      # Make rating predictions in the final layer.
      tf.keras.layers.Dense(1)
    ])

    self.task = tfrs.tasks.Ranking(
      loss=loss,
      metrics=[
        tfr.keras.metrics.NDCGMetric(name="ndcg_metric"),
        tf.keras.metrics.RootMeanSquaredError()
      ]
    )

  def call(self, features):
    # We first convert the id features into embeddings.
    # User embeddings are a [batch_size, embedding_dim] tensor.
    user_embeddings = self.user_embeddings(features["user_id"])

    # Movie embeddings are a [batch_size, num_movies_in_list, embedding_dim]
    # tensor.
    movie_embeddings = self.movie_embeddings(features["movie_title"])

    # We want to concatenate user embeddings with movie emebeddings to pass
    # them into the ranking model. To do so, we need to reshape the user
    # embeddings to match the shape of movie embeddings.
    list_length = features["movie_title"].shape[1]
    user_embedding_repeated = tf.repeat(
        tf.expand_dims(user_embeddings, 1), [list_length], axis=1)

    # Once reshaped, we concatenate and pass into the dense layers to generate
    # predictions.
    concatenated_embeddings = tf.concat(
        [user_embedding_repeated, movie_embeddings], 2)

    return self.score_model(concatenated_embeddings)

  def compute_loss(self, features, training=False):
    labels = features.pop("user_rating")

    scores = self(features)

    return self.task(
        labels=labels,
        predictions=tf.squeeze(scores, axis=-1),
    )

In [67]:
epochs = 30

In [68]:
mse_model = RankingModel(tf.keras.losses.MeanSquaredError())
mse_model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))

In [69]:
mse_model.fit(cached_train, epochs=epochs, verbose=False)

In [70]:
hinge_model = RankingModel(tfr.keras.losses.PairwiseHingeLoss())
hinge_model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))

In [71]:
hinge_model.fit(cached_train, epochs=epochs, verbose=False)

In [72]:
listwise_model = RankingModel(tfr.keras.losses.ListMLELoss())
listwise_model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))

In [73]:
listwise_model.fit(cached_train, epochs=epochs, verbose=False)

In [74]:
mse_model_result = mse_model.evaluate(cached_test, return_dict=True)
print("NDCG of the MSE Model: {:.4f}".format(mse_model_result["ndcg_metric"]))

1/1 [==============================] - 1s 605ms/step - ndcg_metric: 0.6790 - root_mean_squared_error: 3.6327 - loss: 13.1967 - regularization_loss: 0.0000e+00 - total_loss: 13.1967
NDCG of the MSE Model: 0.6790


In [75]:
hinge_model_result = hinge_model.evaluate(cached_test, return_dict=True)
print("NDCG of the pairwise hinge loss model: {:.4f}".format(hinge_model_result["ndcg_metric"]))

1/1 [==============================] - 1s 668ms/step - ndcg_metric: 0.6572 - root_mean_squared_error: 7.2889 - loss: 1.9987 - regularization_loss: 0.0000e+00 - total_loss: 1.9987
NDCG of the pairwise hinge loss model: 0.6572


In [76]:
listwise_model_result = listwise_model.evaluate(cached_test, return_dict=True)
print("NDCG of the ListMLE model: {:.4f}".format(listwise_model_result["ndcg_metric"]))

1/1 [==============================] - 1s 953ms/step - ndcg_metric: 0.6796 - root_mean_squared_error: 7.2673 - loss: 4.7875 - regularization_loss: 0.0000e+00 - total_loss: 4.7875
NDCG of the ListMLE model: 0.6796
